import { Download, FileWarning, History as HistoryIcon, LoaderCircle, LogIn, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { startLogin } from "@/const";
import { AcademicDisclaimer } from "@/components/ResearchDisclaimers";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { copyFor } from "@/contexts/pageCopy";
import { useLanguage } from "@/contexts/LanguageContext";

const CLEAR_PHRASE = "DELETE_ALL_RESEARCH_HISTORY";

function displayClass(value: string | null, noClass: string) { return value ? value.replace("_", " ") : noClass; }

export default function History() {
  const { language } = useLanguage();
  const text = copyFor(language).history;
  const { isAuthenticated, loading } = useAuth();
  const [query, setQuery] = useState(""); const [classFilter, setClassFilter] = useState("all"); const [confirmOpen, setConfirmOpen] = useState(false); const [confirmation, setConfirmation] = useState("");
  const utils = trpc.useUtils(); const recordsQuery = trpc.scans.list.useQuery(undefined, { enabled: isAuthenticated });
  const deleteOne = trpc.scans.deleteOne.useMutation({ onSuccess: () => utils.scans.list.invalidate() });
  const artifactDownload = trpc.scans.getArtifactDownload.useQuery;
  const deleteAll = trpc.scans.deleteAll.useMutation({ onSuccess: () => { setConfirmOpen(false); setConfirmation(""); utils.scans.list.invalidate(); } });
  const records = useMemo(() => (recordsQuery.data ?? []).filter(record => (record.scanId.toLowerCase().includes(query.toLowerCase()) || record.mode.includes(query.toLowerCase())) && (classFilter === "all" || record.predictedClass === classFilter)), [recordsQuery.data, query, classFilter]);
  return <div className="mx-auto max-w-6xl space-y-6"><div><h1 className="text-3xl font-semibold tracking-tight">{text.title}</h1><p className="mt-3 max-w-3xl leading-7 text-slate-600">{text.intro}</p></div><AcademicDisclaimer />
    {!loading && !isAuthenticated ? <section className="rounded-2xl border border-slate-200 bg-white p-8 text-center shadow-sm"><LogIn className="mx-auto size-8 text-teal-800" /><h2 className="mt-4 text-lg font-semibold">{text.signIn}</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-600">{text.signInDetail}</p><button type="button" onClick={() => startLogin()} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-teal-800 px-4 py-2.5 text-sm font-semibold text-white"><LogIn className="size-4" />{text.signIn}</button></section> : <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-1 flex-col gap-3 sm:flex-row"><label className="relative block max-w-md flex-1"><span className="sr-only">{text.search}</span><Search className="pointer-events-none absolute left-3 top-3 size-4 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} className="w-full rounded-xl border border-slate-300 py-2.5 pl-9 pr-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-200" placeholder={text.search} /></label><label><span className="sr-only">{text.result}</span><select value={classFilter} onChange={event => setClassFilter(event.target.value)} className="w-full rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-sm focus:border-teal-700 focus:outline-none focus:ring-2 focus:ring-teal-200"><option value="all">{text.outcomes}</option><option value="glioma">Glioma</option><option value="meningioma">Meningioma</option><option value="pituitary">Pituitary</option><option value="no_tumor">No tumor</option></select></label></div>{records.length > 0 && <button type="button" onClick={() => setConfirmOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-rose-300 px-3 py-2.5 text-sm font-semibold text-rose-800 hover:bg-rose-50"><Trash2 className="size-4" />{text.deleteAll}</button>}</div>
      {confirmOpen && <div className="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4" role="alertdialog" aria-labelledby="clear-history-title"><h2 id="clear-history-title" className="font-semibold text-rose-950">{text.remove}</h2><p className="mt-2 text-sm leading-6 text-rose-900">{text.removeDetail} <code className="rounded bg-white px-1.5 py-0.5">{CLEAR_PHRASE}</code></p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={confirmation} onChange={event => setConfirmation(event.target.value)} className="min-w-0 flex-1 rounded-lg border border-rose-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-rose-500" aria-label={text.remove} /><button type="button" disabled={confirmation !== CLEAR_PHRASE || deleteAll.isPending} onClick={() => deleteAll.mutate({ confirmation: CLEAR_PHRASE })} className="rounded-lg bg-rose-700 px-3 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:bg-slate-300">{deleteAll.isPending ? text.preparing : text.confirm}</button><button type="button" onClick={() => { setConfirmOpen(false); setConfirmation(""); }} className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700">{text.cancel}</button></div>{deleteAll.error && <p className="mt-2 text-sm text-rose-800">{deleteAll.error.message}</p>}</div>}
      {recordsQuery.isLoading || loading ? <div className="grid min-h-56 place-items-center"><LoaderCircle className="size-7 animate-spin text-teal-700" /></div> : recordsQuery.error ? <div className="mt-6 rounded-xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-900"><FileWarning className="mr-2 inline size-5" />History could not be loaded: {recordsQuery.error.message}</div> : records.length === 0 ? <div className="mt-6 grid min-h-56 place-items-center rounded-xl bg-slate-50 text-center"><div><HistoryIcon className="mx-auto size-8 text-slate-400" /><h2 className="mt-3 font-semibold">{query || classFilter !== "all" ? text.noMatches : text.empty}</h2><p className="mt-1 max-w-md text-sm leading-6 text-slate-600">{text.emptyDetail}</p></div></div> : <div className="mt-6 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-[0.08em] text-slate-500"><tr><th className="pb-3 pr-4">{text.scan}</th><th className="pb-3 pr-4">{text.result}</th><th className="pb-3 pr-4">{text.status}</th><th className="pb-3 pr-4">{text.created}</th><th className="pb-3 pr-4">{text.artifacts}</th><th className="pb-3">{text.actions}</th></tr></thead><tbody>{records.map(record => <tr key={record.scanId} className="border-b border-slate-100 align-top"><td className="py-4 pr-4"><code className="text-xs text-slate-700">{record.scanId.slice(0, 8)}…</code><p className="mt-1 text-xs text-slate-500">{record.mode} · {record.modelVersion}</p></td><td className="py-4 pr-4 capitalize">{displayClass(record.predictedClass, text.noConfidence)}<p className="mt-1 text-xs text-slate-500">{record.confidenceScore === null ? text.noConfidence : `${text.modelConfidence}: ${(record.confidenceScore * 100).toFixed(1)}%`}</p></td><td className="py-4 pr-4"><span className={`rounded-full px-2 py-1 text-xs font-semibold ${record.manualReviewRecommended ? "bg-amber-100 text-amber-900" : "bg-emerald-100 text-emerald-900"}`}>{record.manualReviewRecommended ? text.manual : record.status}</span></td><td className="py-4 pr-4 text-xs text-slate-600">{new Date(record.createdAt).toLocaleString()}</td><td className="py-4 pr-4"><div className="flex flex-wrap gap-2">{record.artifacts.length ? record.artifacts.map(artifact => <ArtifactDownloadButton key={artifact.id} artifactId={artifact.id} artifactType={artifact.artifactType} scanId={record.scanId} getArtifactDownload={artifactDownload} />) : <span className="text-xs text-slate-500">{text.noArtifacts}</span>}</div></td><td className="py-4"><button type="button" onClick={() => deleteOne.mutate({ scanId: record.scanId })} disabled={deleteOne.isPending} className="inline-flex items-center gap-1 text-xs font-semibold text-rose-700 hover:underline"><Trash2 className="size-3" />{text.delete}</button></td></tr>)}</tbody></table></div>}</section>}</div>;
}

function ArtifactDownloadButton({ artifactId, artifactType, scanId, getArtifactDownload }: { artifactId: number; artifactType: string; scanId: string; getArtifactDownload: typeof trpc.scans.getArtifactDownload.useQuery }) {
  const artifact = getArtifactDownload({ artifactId }, { enabled: false, retry: false });
  const download = () => artifact.refetch().then(result => {
    if (result.data?.storageUrl) window.location.assign(result.data.storageUrl);
  });
  return <button type="button" onClick={download} disabled={artifact.isFetching} className="inline-flex items-center gap-1 rounded-lg border border-teal-200 bg-teal-50 px-2 py-1 text-xs font-semibold text-teal-800 hover:bg-teal-100 disabled:cursor-not-allowed disabled:opacity-60" aria-label={`Download ${artifactType} for scan ${scanId}`}><Download className="size-3" />{artifact.isFetching ? "Preparing…" : artifactType.replaceAll("_", " ")}</button>;
}
