import { ArrowRight, BrainCircuit, ChartNoAxesCombined, FileCheck2, Layers3, ShieldAlert } from "lucide-react";
import { Link } from "wouter";
import { AcademicDisclaimer } from "@/components/ResearchDisclaimers";
import { copyFor } from "@/contexts/pageCopy";
import { useLanguage } from "@/contexts/LanguageContext";

const featureIcons = [Layers3, BrainCircuit, ShieldAlert, FileCheck2];

export default function Home() {
  const { language } = useLanguage();
  const text = copyFor(language).home;
  return <div className="mx-auto max-w-6xl space-y-7"><section className="overflow-hidden rounded-3xl bg-[radial-gradient(circle_at_top_right,_#d9f2ef,_transparent_34%),linear-gradient(135deg,_#0c3b3a,_#0f5953)] px-6 py-10 text-white shadow-xl sm:px-10 sm:py-14"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-200">{text.eyebrow}</p><h1 className="mt-4 max-w-3xl text-4xl font-semibold tracking-tight sm:text-5xl">{text.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-teal-50">{text.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/analyse" className="inline-flex items-center gap-2 rounded-xl bg-white px-4 py-3 text-sm font-semibold text-teal-950 shadow-sm transition hover:bg-teal-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-white">{text.begin} <ArrowRight className="size-4" /></Link><Link href="/methodology" className="inline-flex items-center gap-2 rounded-xl border border-teal-300/50 px-4 py-3 text-sm font-semibold text-white transition hover:bg-white/10 focus:outline-none focus-visible:ring-2 focus-visible:ring-white">{text.methodology}</Link></div></section><AcademicDisclaimer /><section className="grid gap-4 sm:grid-cols-2">{text.features.map(([title, detail], index) => { const Icon = featureIcons[index]!; return <article key={title} className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><span className="grid size-10 place-items-center rounded-xl bg-teal-50 text-teal-800"><Icon className="size-5" /></span><h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{detail}</p></article>; })}</section><section className="grid gap-4 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm lg:grid-cols-[1fr_auto]"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-teal-700">{text.modelStatus}</p><h2 className="mt-2 text-xl font-semibold">{text.modelTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{text.modelDetail}</p></div><Link href="/performance" className="inline-flex h-fit items-center gap-2 self-end rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-700 transition hover:border-teal-300 hover:bg-teal-50">{text.evidence} <ChartNoAxesCombined className="size-4" /></Link></section></div>;
}
