import { BrainCircuit, ChevronRight, Languages, Menu, X } from "lucide-react";
import { useState } from "react";
import { Link, useLocation } from "wouter";
import { AcademicDisclaimer } from "./ResearchDisclaimers";
import { useLanguage } from "@/contexts/LanguageContext";

type NavItem = { href: string; key: "home" | "analyze" | "results" | "history" | "methodology" | "performance" | "limitations" | "about" };
const navigation: NavItem[] = [{ href: "/", key: "home" }, { href: "/analyse", key: "analyze" }, { href: "/results", key: "results" }, { href: "/history", key: "history" }, { href: "/methodology", key: "methodology" }, { href: "/performance", key: "performance" }, { href: "/limitations", key: "limitations" }, { href: "/about", key: "about" }];

export function AppShell({ children }: { children: React.ReactNode }) {
  const [location] = useLocation(); const [open, setOpen] = useState(false); const { language, setLanguage, t } = useLanguage(); const active = navigation.find(item => item.href === location) ?? navigation[0];
  const links = (mobile = false) => <nav aria-label={t("navigation")} className={mobile ? "grid gap-1" : "grid gap-1.5"}>{navigation.map(item => { const selected = location === item.href; return <Link key={item.href} href={item.href} onClick={() => setOpen(false)} className={`group flex items-center justify-between rounded-xl px-3 py-2.5 text-sm transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-700 ${selected ? "bg-teal-800 text-white" : "text-slate-600 hover:bg-teal-50 hover:text-teal-950"}`} aria-current={selected ? "page" : undefined}><span>{t(item.key)}</span><ChevronRight className={`size-4 ${selected ? "text-teal-100" : "text-slate-300 group-hover:text-teal-700"}`} aria-hidden="true" /></Link>; })}</nav>;
  return <div className="min-h-screen bg-[#f4f7f7] text-slate-900"><header className="sticky top-0 z-40 border-b border-slate-200 bg-white/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-[1500px] items-center justify-between px-4 sm:px-6"><Link href="/" className="flex items-center gap-3 rounded-lg focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-700"><span className="grid size-9 place-items-center rounded-xl bg-teal-800 text-white shadow-sm"><BrainCircuit className="size-5" aria-hidden="true" /></span><span><span className="block text-sm font-semibold tracking-tight">NeuroInsight AI</span><span className="block text-[11px] font-medium uppercase tracking-[0.14em] text-teal-700">Research workspace</span></span></Link><div className="flex items-center gap-2"><button type="button" onClick={() => setLanguage(language === "en" ? "hi" : "en")} className="inline-flex items-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium text-slate-700 shadow-sm transition hover:border-teal-300 hover:bg-teal-50 focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-700" aria-label={`Switch language to ${language === "en" ? "Hindi" : "English"}`}><Languages className="size-4" aria-hidden="true" />{t("language")}</button><button type="button" className="grid size-10 place-items-center rounded-lg border border-slate-200 text-slate-700 md:hidden focus:outline-none focus-visible:ring-2 focus-visible:ring-teal-700" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-navigation" aria-label="Toggle navigation">{open ? <X className="size-5" /> : <Menu className="size-5" />}</button></div></div><div className="border-t border-amber-200 bg-amber-50 px-4 py-1.5 text-center text-[11px] font-medium leading-4 text-amber-950 md:hidden" role="note">{t("academic")}</div></header>{open && <div id="mobile-navigation" className="border-b border-slate-200 bg-white px-4 py-4 shadow-lg md:hidden">{links(true)}</div>}<div className="mx-auto grid max-w-[1500px] md:grid-cols-[230px_minmax(0,1fr)]"><aside className="sticky top-16 hidden h-[calc(100vh-4rem)] border-r border-slate-200 bg-white p-4 md:block"><p className="mb-3 px-3 text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-400">{t("navigation")}</p>{links()}<div className="mt-6 border-t border-slate-100 pt-5"><AcademicDisclaimer compact /></div></aside><main className="min-w-0 px-4 py-6 sm:px-6 lg:px-9 lg:py-8"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.16em] text-teal-700">{t(active.key)}</p>{children}</main></div></div>;
}
