import { Box, Maximize2, Rotate3D, ZoomIn } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";

type ViewerProps = { artifactUrl?: string; scanId?: string };

export function Volume3DViewer({ artifactUrl, scanId }: ViewerProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const objectRef = useRef<THREE.Object3D | null>(null); const initialRotation = useRef(new THREE.Euler()); const initialDistance = useRef(4); const cameraRef = useRef<THREE.PerspectiveCamera | null>(null);
  const [opacity, setOpacity] = useState(0.75); const [highlight, setHighlight] = useState(true); const [error, setError] = useState(""); const [dragStart, setDragStart] = useState<{ x: number; y: number } | null>(null);
  useEffect(() => {
    if (!artifactUrl || !canvasRef.current) return;
    const canvas = canvasRef.current; const scene = new THREE.Scene(); scene.background = new THREE.Color("#eef5f4");
    const camera = new THREE.PerspectiveCamera(40, canvas.clientWidth / Math.max(canvas.clientHeight, 1), 0.1, 100); camera.position.set(0, 0, initialDistance.current); cameraRef.current = camera;
    const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, alpha: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2)); renderer.setSize(canvas.clientWidth, canvas.clientHeight, false);
    scene.add(new THREE.HemisphereLight(0xffffff, 0x315c5b, 2)); const light = new THREE.DirectionalLight(0xffffff, 2); light.position.set(3, 4, 5); scene.add(light);
    const loader = new GLTFLoader(); loader.load(artifactUrl, gltf => { const object = gltf.scene; object.traverse(node => { if (node instanceof THREE.Mesh) { const material = node.material as THREE.MeshStandardMaterial; material.transparent = true; material.opacity = opacity; material.color.set(highlight ? "#cf3e5e" : "#249b8f"); material.roughness = 0.48; material.metalness = 0.05; } }); const box = new THREE.Box3().setFromObject(object); const center = box.getCenter(new THREE.Vector3()); object.position.sub(center); const size = box.getSize(new THREE.Vector3()).length(); initialDistance.current = Math.max(size * 1.7, 2.5); camera.position.z = initialDistance.current; initialRotation.current = object.rotation.clone(); objectRef.current = object; scene.add(object); }, undefined, () => setError("The stored 3D artifact could not be rendered. Verify that it is a compatible GLB geometry."));
    const render = () => { renderer.render(scene, camera); }; render(); const observer = new ResizeObserver(() => { const width = canvas.clientWidth; const height = Math.max(canvas.clientHeight, 1); renderer.setSize(width, height, false); camera.aspect = width / height; camera.updateProjectionMatrix(); render(); }); observer.observe(canvas);
    const frame = window.setInterval(render, 50);
    return () => { window.clearInterval(frame); observer.disconnect(); renderer.dispose(); objectRef.current = null; };
  }, [artifactUrl]);
  useEffect(() => { const object = objectRef.current; if (!object) return; object.traverse(node => { if (node instanceof THREE.Mesh) { const material = node.material as THREE.MeshStandardMaterial; material.opacity = opacity; material.color.set(highlight ? "#cf3e5e" : "#249b8f"); material.needsUpdate = true; } }); }, [opacity, highlight]);
  const reset = () => { if (objectRef.current) objectRef.current.rotation.copy(initialRotation.current); if (cameraRef.current) cameraRef.current.position.z = initialDistance.current; };
  if (!artifactUrl) return <section className="rounded-2xl border border-dashed border-slate-300 bg-white p-6" aria-labelledby="viewer-title"><div className="flex gap-3"><Box className="mt-0.5 size-6 text-teal-800" /><div><h2 id="viewer-title" className="text-lg font-semibold">Compatible 3D geometry unavailable</h2><p className="mt-2 text-sm leading-6 text-slate-600">A rotate, zoom, opacity, and highlighting viewer is enabled only after a verified segmentation service stores a compatible GLB geometry for this scan. No algorithmic geometry is estimated by the dashboard.</p><p className="mt-3 text-xs leading-5 text-slate-500">Any geometry shown here is algorithmically estimated research output, not an anatomical or clinical ground truth.</p></div></div></section>;
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-labelledby="viewer-title"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 id="viewer-title" className="text-lg font-semibold">Interactive 3D segmentation geometry</h2><p className="mt-1 text-sm text-slate-600">Scan {scanId ? `${scanId.slice(0, 8)}…` : "artifact"}. Drag to rotate and use the mouse wheel to zoom.</p></div><p className="max-w-sm text-right text-xs leading-5 text-slate-500">Geometry is algorithmically estimated from a segmentation mask. It is not an anatomical or clinical ground truth.</p></div>{error ? <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-900">{error}</p> : <canvas ref={canvasRef} className="mt-4 h-80 w-full rounded-xl border border-slate-200 bg-slate-50" aria-label="Interactive three-dimensional segmentation geometry" onPointerDown={event => { event.currentTarget.setPointerCapture(event.pointerId); setDragStart({ x: event.clientX, y: event.clientY }); }} onPointerMove={event => { if (!dragStart || !objectRef.current) return; objectRef.current.rotation.y += (event.clientX - dragStart.x) * 0.01; objectRef.current.rotation.x += (event.clientY - dragStart.y) * 0.01; setDragStart({ x: event.clientX, y: event.clientY }); }} onPointerUp={() => setDragStart(null)} onWheel={event => { event.preventDefault(); if (cameraRef.current) cameraRef.current.position.z = Math.min(Math.max(cameraRef.current.position.z + event.deltaY * 0.006, 1), 10); }} />}
    <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto_auto]"><label className="flex items-center gap-3 rounded-xl bg-slate-50 px-3 py-2 text-sm"><span className="whitespace-nowrap">Mask opacity</span><input type="range" min="0.1" max="1" step="0.05" value={opacity} onChange={event => setOpacity(Number(event.target.value))} className="w-full accent-teal-700" aria-label="Segmentation geometry opacity" /></label><button type="button" onClick={() => setHighlight(value => !value)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"><ZoomIn className="size-4" />{highlight ? "Tumor highlight on" : "Tumor highlight off"}</button><button type="button" onClick={reset} className="inline-flex items-center justify-center gap-2 rounded-xl border border-slate-300 px-3 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50"><Rotate3D className="size-4" />Reset view</button></div><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><Maximize2 className="size-3" />Compatible stored geometries support pointer rotation and wheel zoom.</p></section>;
}
